// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tutorial

import (
	"context"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error)
	DeleteUrls(ctx context.Context, id int64) error
	GetUrlById(ctx context.Context, id int64) (Url, error)
	GetUrlByShortUrl(ctx context.Context, short string) (Url, error)
	ListUrls(ctx context.Context) ([]Url, error)
	UpdateUrl(ctx context.Context, arg UpdateUrlParams) error
}

var _ Querier = (*Queries)(nil)
